// Design for Lab3
// Request class demonstrate request info
// It has a unique request id named requestID
// departureStationID and destinyStationID are the stationID generated by rand()
// businessClass is the bool var for seat class. True means is Business otherwise couch
// numOfPassangers is the number of passengers in this request (1-8)
// departureTime that the passengers need to departure at that moment. 

#ifndef REQUEST_H
#define REQUEST_H

class Request{
    public:
        Request(int num, int time);
        ~Request();
        Request(const Request &r); // copy constructor
        Request(Request &&r); //move constructor
        int getRequestID();
        int getDepartureStationID();
        int getDestinyStationID();
        int getNumOfPassengers();
        int getDepartureTime();
        bool isBusinessClass();
        bool isAvailabletrain(int trainID); 
        void assignSeat(int trainID);
        int selectTrain();
        bool isbegin(int trainID);
        bool isfinished(int trainID);

    private:
        int requestID;
        int departureStationID;
        int destinyStationID;
        bool businessClass;
        int numOfPassengers;
        int departureTime;

};

#endif